name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
    - name: Create bin dir
      run: mkdir -p "${HOME}/go/bin"

    - name: Create src dir
      run: mkdir -p "${HOME}/go/src"

    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            ${HOME}/go/bin/dep ensure
        fi

    - name: Build
      run: go build -v .
